"""
Tests for Frame Sampling and Observation.

Run against real clips generated by ffmpeg, because what is being tested is
whether frames actually come out of a file and in what order — which a mock
could only confirm about itself.
"""

import pytest

from src.core.ffmpeg_tools import MediaToolchain
from src.backends.adapter import BackendError
from src.identifier.frames import SAMPLE_WIDTH, FrameSampler
from src.identifier.observe import build_prompt, parse_reply


@pytest.fixture
def sampler(ffmpeg_available):
    if not ffmpeg_available:
        pytest.skip("ffmpeg is not installed")
    return FrameSampler(MediaToolchain())


# --- SAMPLING ---


def test_frames_come_out_in_time_order(sampler, clips, tmp_path):
    """
    Order is the only motion information the observation pass gets.

    The frames are sampled across a shot and read as a sequence, so a shuffled
    list would describe a camera move that never happened.
    """
    frames = sampler.sample(clips["pal"], tmp_path, count=4)

    assert len(frames) == 4
    assert all(frame.is_file() for frame in frames)
    assert [frame.name for frame in frames] == sorted(frame.name for frame in frames)


def test_frames_are_small_on_purpose(sampler, clips, tmp_path):
    """
    Nothing about judging framing needs full resolution, and small frames keep
    API calls cheap, local inference quick, and fit CLI tools that only accept
    preview-sized images.
    """
    frame = sampler.sample(clips["pal"], tmp_path, count=1)[0]

    probe = MediaToolchain().run_ffprobe([
        "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=width", "-of", "csv=p=0", str(frame),
    ])

    assert int(probe.stdout.strip()) == SAMPLE_WIDTH


def test_one_frame_is_taken_from_the_middle():
    """
    A first frame is often a part-completed move or a character entering, and
    summarises a shot worse than anything from its middle.
    """
    offsets = FrameSampler._offsets(duration=10.0, count=1)

    assert offsets == [5.0]


def test_frames_avoid_both_ends_of_the_shot():
    """
    The first and last frames of a cut often catch a residual blend from the
    edit, which describes the transition rather than the shot.
    """
    offsets = FrameSampler._offsets(duration=10.0, count=5)

    assert offsets[0] > 0, "never the very first frame"
    assert offsets[-1] < 10.0, "never the very last"
    assert offsets == sorted(offsets)


def test_a_file_with_no_video_is_refused_by_name(sampler, clips, tmp_path):
    """
    Saying so here names the file. Returning an empty list would read
    downstream as a shot nothing could be said about, which hides the cause.
    """
    with pytest.raises(RuntimeError):
        sampler.sample(clips["audio_only"], tmp_path)


def test_a_missing_file_is_refused(sampler, tmp_path):
    with pytest.raises(RuntimeError):
        sampler.sample(tmp_path / "not-here.mp4", tmp_path)


# --- THUMBNAILS ---


def test_a_thumbnail_is_written_for_the_export(sampler, clips, tmp_path):
    target = tmp_path / "thumbs" / "shot_001.jpg"

    written = sampler.thumbnail(clips["pal"], target)

    assert written == target
    assert target.is_file(), "the directory is created rather than assumed"


# --- OBSERVATION ---


def test_a_command_with_nowhere_for_images_is_refused(tmp_path):
    """
    Silently dropping the frames is the worst failure available here: the model
    answers from the prompt alone, the reply looks exactly like an observation,
    and every field in it is invented.

    Found on the first real run — the images never reached the CLI, and only
    because that model pushed back did it not return seven fabricated fields.
    """
    import sys

    from src.backends.command import CommandBackend
    from src.core.config import BackendConfig

    frame = tmp_path / "f.jpg"
    frame.write_bytes(b"\xff\xd8\xff")

    backend = CommandBackend(
        BackendConfig(kind="command", command=[sys.executable, "-c", "pass"])
    )

    with pytest.raises(BackendError, match="nowhere to put them"):
        backend.send("describe this", images=[frame])


def test_a_model_reporting_no_image_is_an_error_not_a_description():
    """The whole point of the NO IMAGE instruction in the prompt."""
    with pytest.raises(BackendError, match="no image reached it"):
        parse_reply("NO IMAGE")


def test_the_prompt_refuses_film_terminology_and_invention():
    """
    Both refusals are load-bearing. Terminology because inconsistent vocabulary
    is fatal when the next step compares text to text; invention because a
    misconfigured backend must not read as a result.
    """
    prompt = build_prompt(6)

    assert "close-up" in prompt and "Do NOT use film" in prompt
    assert "NO IMAGE" in prompt
    assert "motion" in prompt, "six frames carry motion"


def test_a_still_is_never_asked_about_motion():
    """There is none to report, and asking for it invites invention."""
    assert "motion" not in build_prompt(1, is_still=True)
