"""
Tests for Source Probing.

Runs against clips generated by the fixtures in conftest.py, so every frame
rate, frame count and geometry asserted here is known exactly rather than
approximately.
"""

from fractions import Fraction
from pathlib import Path

import pytest

from src.core.models import SourceInfo
from src.media.probe import SourceProbe

# --- FIXTURES ---


@pytest.fixture
def probe(toolchain):
    return SourceProbe(toolchain)


def make_source(**overrides) -> SourceInfo:
    """A probed source with sensible defaults, for the pure-maths tests."""
    fields = {
        "path": "reel.mov",
        "width": 1920,
        "height": 1080,
        "fps_numerator": 25,
        "fps_denominator": 1,
        "frame_count": 1500,
        "codec": "prores",
    }
    fields.update(overrides)
    return SourceInfo(**fields)


# --- PROBING ---


def test_reads_geometry_and_codec(probe, clips):
    source = probe.probe(clips["pal"])

    assert source.width == 320
    assert source.height == 240
    assert source.codec == "h264"


def test_reads_the_pixel_format(probe, clips):
    """Carried through to the mezzanine so bit depth survives the round trip."""
    assert probe.probe(clips["pal"]).pixel_format == "yuv420p"


def test_reads_an_exact_frame_count(probe, clips):
    """Two seconds at 25 fps is 50 frames — not 49, not 51."""
    assert probe.probe(clips["pal"]).frame_count == 50


def test_frame_rate_is_kept_as_a_rational(probe, clips):
    """
    23.976 must survive as 24000/1001.

    Rounding it to 23.976 drifts a frame roughly every forty seconds, which is
    the single most likely way for this tool to be quietly wrong.
    """
    source = probe.probe(clips["film"])

    assert source.fps_numerator == 24000
    assert source.fps_denominator == 1001
    assert Fraction(source.fps_numerator, source.fps_denominator) == Fraction(24000, 1001)


def test_film_clip_frame_count(probe, clips):
    """Two seconds at 23.976 is 48 frames."""
    assert probe.probe(clips["film"]).frame_count == 48


def test_reads_the_start_timecode(probe, clips):
    """A source starting at 10:00:00:00 must report exactly that, not zero."""
    assert probe.probe(clips["pal"]).start_timecode == "10:00:00:00"


def test_missing_timecode_defaults_to_zero(probe, clips):
    """A file with no timecode track starts at zero rather than failing."""
    assert probe.probe(clips["film"]).start_timecode == "00:00:00:00"


# --- VARIABLE FRAME RATE ---


def test_constant_frame_rate_is_not_flagged(probe, clips):
    assert probe.probe(clips["pal"]).is_variable_frame_rate is False
    assert probe.probe(clips["film"]).is_variable_frame_rate is False


def test_variable_frame_rate_is_flagged(probe, clips):
    """
    A VFR source has no stable frame-to-time mapping, so every boundary drifts.

    The pipeline refuses these; the probe's job is only to notice.
    """
    assert probe.probe(clips["vfr"]).is_variable_frame_rate is True


def test_unknown_average_rate_is_not_vfr():
    """Some containers report avg_frame_rate as 0/0 — that is unknown, not variable."""
    assert SourceProbe._is_variable_frame_rate({"r_frame_rate": "25/1", "avg_frame_rate": "0/0"}) is False
    assert SourceProbe._is_variable_frame_rate({"r_frame_rate": "25/1", "avg_frame_rate": "25/1"}) is False
    assert SourceProbe._is_variable_frame_rate({"r_frame_rate": "25/1", "avg_frame_rate": "125/7"}) is True


# --- FAILURE CASES ---


def test_missing_file_raises(probe, tmp_path):
    with pytest.raises(FileNotFoundError):
        probe.probe(tmp_path / "nothing-here.mov")


def test_file_without_video_raises(probe, clips):
    """An audio-only file is not a mini cut, and says so rather than probing empty."""
    with pytest.raises(ValueError, match="No video stream"):
        probe.probe(clips["audio_only"])


def test_unreadable_file_raises(probe, tmp_path):
    """A file that is not media at all fails with ffprobe's own reason attached."""
    broken = tmp_path / "not-a-movie.mov"
    broken.write_text("this is not a video file")

    with pytest.raises(ValueError):
        probe.probe(broken)


@pytest.mark.parametrize("rate", [None, "", "25", "0/0", "25/0", "abc/def", "-25/1"])
def test_bad_frame_rates_are_rejected(rate):
    """A missing or zero rate must fail loudly — every later calculation divides by it."""
    with pytest.raises(ValueError):
        SourceProbe._parse_rate(rate, Path("reel.mov"))


def test_frame_rate_parsing_keeps_both_parts():
    assert SourceProbe._parse_rate("24000/1001", Path("reel.mov")) == (24000, 1001)
    assert SourceProbe._parse_rate("25/1", Path("reel.mov")) == (25, 1)


# --- TIMECODE LOCATIONS ---


def test_timecode_is_found_in_any_stream():
    """ffmpeg writes the timecode to the video stream and to a tmcd data stream."""
    streams = [
        {"codec_type": "video", "tags": {"handler_name": "VideoHandler"}},
        {"codec_type": "data", "tags": {"timecode": "01:00:00:00"}},
    ]
    assert SourceProbe._start_timecode(streams, {}) == "01:00:00:00"


def test_timecode_falls_back_to_container_tags():
    """Some files carry it only at container level."""
    assert SourceProbe._start_timecode([], {"tags": {"timecode": "09:59:50:00"}}) == "09:59:50:00"


def test_timecode_defaults_to_zero_when_absent():
    assert SourceProbe._start_timecode([{"codec_type": "video"}], {}) == "00:00:00:00"


# --- CROP DETECTION ---


def test_full_frame_reports_no_crop(probe, clips):
    """A source with no bars must return None, not a full-frame crop string."""
    source = probe.probe(clips["pal"])

    assert probe.detect_crop(source) is None


def test_letterbox_is_detected(probe, clips):
    """
    A 320x180 picture padded into a 320x240 frame has 30px bars top and bottom.

    round=2 keeps the reported crop on the true edge; cropdetect's default
    rounding to 16 would eat several rows of real picture.
    """
    source = probe.probe(clips["letterbox"])

    assert probe.detect_crop(source) == "320:180:0:30"


def test_sample_offsets_cover_a_long_file():
    """Samples are spread across the file and never start at the very end."""
    offsets = SourceProbe._sample_offsets(600.0)

    assert len(offsets) == 5
    assert offsets == sorted(offsets), "samples should run in order"
    assert offsets[0] > 0, "the first moments are the most likely to be a fade"
    assert offsets[-1] <= 600.0 - 10


def test_short_file_is_sampled_once():
    """A file shorter than one sample window is read from the start, once."""
    assert SourceProbe._sample_offsets(4.0) == [0.0]


# --- DISK ESTIMATION ---


def test_disk_estimate_matches_the_reference_figure(probe):
    """
    One minute of 1080p24 is the reference case, doubled for the splits.

    0.25 GB/min of all-intra mezzanine plus the same again of shot files.
    """
    one_minute = make_source(fps_numerator=24, frame_count=1440)

    assert probe.estimate_disk_required(one_minute) == pytest.approx(0.5)


def test_disk_estimate_scales_with_resolution(probe):
    """4K is four times the pixels of HD, so four times the disk."""
    hd = probe.estimate_disk_required(make_source(width=1920, height=1080))
    uhd = probe.estimate_disk_required(make_source(width=3840, height=2160))

    assert uhd == pytest.approx(hd * 4)


def test_disk_estimate_scales_with_frame_rate(probe):
    """Forty-eight frames a second is twice the data of twenty-four, same duration."""
    at_24 = probe.estimate_disk_required(make_source(fps_numerator=24, frame_count=1440))
    at_48 = probe.estimate_disk_required(make_source(fps_numerator=48, frame_count=2880))

    assert at_48 == pytest.approx(at_24 * 2)
